import React from 'react';
import { ChartBarIcon, BanknotesIcon, ArrowTrendingUpIcon, ScaleIcon } from '../constants';

const FAQPage = () => {
    return (
        <div className="p-8 bg-gray-50/50 min-h-screen">
            <header className="mb-8">
                <h1 className="text-3xl font-bold text-gray-900">Glossary & FAQ</h1>
                <p className="text-gray-600 mt-1">Common real estate investing terms, formulas, and industry standards.</p>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

                <DefinitionCard
                    title="Cap Rate (Capitalization Rate)"
                    icon={ArrowTrendingUpIcon}
                    definition="The rate of return on a real estate investment property based on the income that the property is expected to generate. It represents the potential return if the property was purchased with all cash."
                    formula="Net Operating Income (NOI) / Purchase Price"
                    standard="4% - 8%"
                    note="Lower cap rates generally imply lower risk (better area) but lower cash flow. Higher cap rates imply higher risk but potentially better cash flow."
                />

                <DefinitionCard
                    title="All-in Cap Rate"
                    icon={ArrowTrendingUpIcon}
                    definition="Similar to Cap Rate, but it accounts for the total capital required to acquire and stabilize the asset, including renovation costs and closing fees."
                    formula="Net Operating Income (NOI) / (Purchase Price + Rehab Costs + Closing Costs)"
                    standard="> Market Cap Rate (e.g. 6% - 8%+)"
                    note="This is a more accurate measure for properties requiring work. You want this to be 1-2% higher than the market Cap Rate to justify the effort."
                />

                <DefinitionCard
                    title="Cash-on-Cash Return (CoC)"
                    icon={BanknotesIcon}
                    definition="A rate of return ratio that calculates the total cash earned on the total cash invested in a property. It measures the return on the actual dollars you put into the deal."
                    formula="Annual Pre-Tax Cash Flow / Total Cash Invested"
                    standard="8% - 12%+"
                    note="Total Cash Invested includes Down Payment, Closing Costs, and Rehab Costs out of pocket. This is often the most important metric for investors using leverage."
                />

                <DefinitionCard
                    title="Cash Flow (With Debt)"
                    icon={BanknotesIcon}
                    definition="The net amount of cash moving in or out of the investment after all operating expenses and mortgage payments have been made. This is your 'take home' profit."
                    formula="Net Operating Income (NOI) - Annual Debt Service"
                    standard="$100 - $200+ per door / month"
                    note="Positive cash flow ensures the property pays for itself and provides passive income. Negative cash flow means you are feeding the property monthly."
                />

                <DefinitionCard
                    title="DSCR (Debt Service Coverage Ratio)"
                    icon={ScaleIcon}
                    definition="A measurement of the cash flow available to pay current debt obligations. Lenders use this to assess the borrower's ability to repay the loan."
                    formula="Net Operating Income (NOI) / Total Debt Service"
                    standard="> 1.20 or 1.25"
                    note="A DSCR of 1.0 means you break even. Lenders typically require 1.20 or higher to ensure a safety margin."
                />

                <DefinitionCard
                    title="Monthly Cash Flow (No Debt)"
                    icon={ChartBarIcon}
                    definition="The monthly income generated by the property if you owned it free and clear (no mortgage). It is equivalent to the Monthly Net Operating Income (NOI)."
                    formula="Net Operating Income (NOI) / 12"
                    standard="N/A"
                    note="This metric helps you understand the pure earning power of the asset irrespective of financing structure."
                />

            </div>

            <header className="mb-8 mt-16">
                <h2 className="text-2xl font-bold text-gray-900">Investment Strategies</h2>
                <p className="text-gray-600 mt-1">Pros and cons of different real estate investment approaches.</p>
            </header>

            <div className="grid grid-cols-1 gap-6">
                <StrategyCard
                    title="Rental (Buy & Hold)"
                    description="The traditional strategy of purchasing a property to rent out for the long term. The goal is to generate monthly cash flow while benefiting from long-term appreciation and tax advantages."
                    pros={[
                        "Passive income stream",
                        "Tax benefits (depreciation, deductions)",
                        "Principal paydown by tenants",
                        "Long-term appreciation"
                    ]}
                    cons={[
                        "Tenant management and vacancies",
                        "Maintenance and repair costs",
                        "Illiquid asset (hard to sell quickly)",
                        "Slow wealth building in the beginning"
                    ]}
                />

                <StrategyCard
                    title="Wholesale"
                    description="Finding a discounted property and assigning the contract to another buyer (usually an investor) for a fee, without ever taking ownership of the property."
                    pros={[
                        "Little to no capital required",
                        "Low financial risk",
                        "Quick cash generation (days/weeks)",
                        "No credit check needed"
                    ]}
                    cons={[
                        "Active income (not passive)",
                        "Requires constant marketing and hustle",
                        "Dependent on finding buyers",
                        "No long-term wealth accumulation or tax benefits"
                    ]}
                />

                <StrategyCard
                    title="Subject-To"
                    description="Buying a property 'subject to' the existing mortgage. The deed transfers to you, but the original loan stays in the seller's name and you make the payments."
                    pros={[
                        "No credit check or bank qualification",
                        "No new loan origination fees",
                        "Often secures low interest rates (from original loan)",
                        "Little cash down required"
                    ]}
                    cons={[
                        "Due-on-sale clause risk (lender could call the loan)",
                        "Seller dependency (if they stop paying other debts)",
                        "Ethical considerations and complexity",
                        "Insurance and title challenges"
                    ]}
                />

                <StrategyCard
                    title="Seller Financing"
                    description="The seller acts as the lender. Instead of getting a bank loan, you make payments directly to the seller based on agreed terms."
                    pros={[
                        "Flexible terms (interest, down payment)",
                        "No bank underwriting or red tape",
                        "Faster closing process",
                        "Good for properties banks won't finance"
                    ]}
                    cons={[
                        "Seller might demand higher interest rates",
                        "Often requires a balloon payment (short term)",
                        "Seller might foreclose aggressively if you miss payments",
                        "Limited inventory (most sellers want cash)"
                    ]}
                />

                <StrategyCard
                    title="BRRRR (Buy, Rehab, Rent, Refinance, Repeat)"
                    description="A strategy to acquire properties with little of your own money left in the deal. You buy a fixer-upper, renovate it, rent it out, and then refinance to pull your initial capital back out to use for the next deal."
                    pros={[
                        "Infinite returns (if 100% capital is returned)",
                        "Rapid portfolio growth",
                        "Recycling the same capital multiple times",
                        "Forces equity creation through rehab"
                    ]}
                    cons={[
                        "High execution risk (rehab costs, appraisal)",
                        "Requires short-term financing (hard money)",
                        "Refinance risk (interest rates, LTV limits)",
                        "Time-intensive and operationally complex"
                    ]}
                />
            </div>
        </div>
    );
};

const DefinitionCard = ({ title, icon: Icon, definition, formula, standard, note }: { title: string, icon: React.ElementType, definition: string, formula: string, standard: string, note: string }) => (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
        <div className="flex items-center mb-4">
            <div className="p-2 bg-brand-blue-light rounded-lg mr-3">
                <Icon className="h-6 w-6 text-brand-blue" />
            </div>
            <h3 className="text-xl font-bold text-gray-800">{title}</h3>
        </div>
        <p className="text-gray-600 text-sm mb-4 leading-relaxed">{definition}</p>

        <div className="space-y-3">
            <div className="bg-gray-50 p-3 rounded-lg">
                <span className="text-xs font-bold text-gray-500 uppercase tracking-wide block mb-1">Formula</span>
                <code className="text-sm font-mono text-brand-blue font-semibold">{formula}</code>
            </div>

            <div className="flex items-start">
                <div className="bg-green-50 px-3 py-2 rounded-lg flex-grow">
                    <span className="text-xs font-bold text-green-800 uppercase tracking-wide block mb-1">Industry Standard</span>
                    <span className="text-sm font-bold text-green-700">{standard}</span>
                </div>
            </div>
        </div>

        <div className="mt-4 pt-4 border-t border-gray-100">
            <p className="text-xs text-gray-500 italic"><span className="font-semibold">Note:</span> {note}</p>
        </div>
    </div>
);

const StrategyCard = ({ title, description, pros, cons }: { title: string, description: string, pros: string[], cons: string[] }) => (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
        <h3 className="text-xl font-bold text-gray-800 mb-3">{title}</h3>
        <p className="text-gray-600 text-sm mb-6 leading-relaxed">{description}</p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="bg-green-50 p-4 rounded-lg">
                <h4 className="text-sm font-bold text-green-800 uppercase tracking-wide mb-3 flex items-center">
                    <span className="mr-2">👍</span> Pros
                </h4>
                <ul className="space-y-2">
                    {pros.map((pro, i) => (
                        <li key={i} className="text-sm text-gray-700 flex items-start">
                            <span className="text-green-500 mr-2">•</span>
                            {pro}
                        </li>
                    ))}
                </ul>
            </div>

            <div className="bg-red-50 p-4 rounded-lg">
                <h4 className="text-sm font-bold text-red-800 uppercase tracking-wide mb-3 flex items-center">
                    <span className="mr-2">👎</span> Cons
                </h4>
                <ul className="space-y-2">
                    {cons.map((con, i) => (
                        <li key={i} className="text-sm text-gray-700 flex items-start">
                            <span className="text-red-500 mr-2">•</span>
                            {con}
                        </li>
                    ))}
                </ul>
            </div>
        </div>
    </div>
);

export default FAQPage;